version: '2'
services:
 jenkins:
   image: jenkinswithdocker/jenkins-with-docker:lts
   ports:
     - 9000:8080
   volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - jenkins-data:/var/jenkins_home
     - jenkins-conf:/var/lib/jenkins
volumes:
 cloudant-data:
 jenkins-data:
 jenkins-conf:
