version: '2'
services:
 uinodejs:
   build: ./Cruise-Site
   image: front-end
   ports:
     - 2000:10010
   links:
     - db
   depends_on:
     - db
   environment:
     - DB_HOST=db
     - DB_PORT=80
     - DB_USER=admin
     - DB_PASS=pass
   volumes:
    - ./Cruise-Site:/appDir/src
 db:
   build: ./Cloudant
   ports:
     - 3000:80
   volumes:
     - cloudant-data:/srv
 swaggerui:
   image: nginx
   ports:
     - 5000:80
   volumes:
     - ./Swagger/swagger-ui:/usr/share/nginx/html/swagger-ui
   links:
     - swaggernodejs
   depends_on:
     - swaggernodejs
 swaggernodejs:
   build: ./Swagger/swagger-nodejs
   ports:
     - 8000:10010
   links:
     - db
   depends_on:
     - db
   environment:
     - DB_HOST=db
     - DB_PORT=80
     - DB_USER=admin
     - DB_PASS=pass
   volumes:
     - ./Swagger/swagger-nodejs:/appDir/src
 jenkins:
   image: jenup
   ports:
     - 9000:8080
   volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - jenkins-data:/var/jenkins_home
     - jenkins-conf:/var/lib/jenkins
volumes:
 cloudant-data:
 jenkins-data:
 jenkins-conf:
